version: '3.9'

services:
  sql-service-db:
    container_name: sql-veniti
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports: 
      - "1433:1433"
    environment:
      SA_PASSWORD: "Q!w2e3r4"
      ACCEPT_EULA: "Y"
    restart: always

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - sql-service-db
